# Generated by Django 4.0 on 2023-03-06 13:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('phone', models.CharField(max_length=64, unique=True, verbose_name='Telefon')),
                ('activated_date', models.DateTimeField(blank=True, null=True, verbose_name='Activlashgan Vaqti')),
                ('is_seller', models.BooleanField(default=False, verbose_name='Sotuvchi holati')),
                ('is_active', models.BooleanField(default=False, verbose_name='Activligi')),
                ('is_staff', models.BooleanField(default=False)),
                ('is_superuser', models.BooleanField(default=False)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.Group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.Permission', verbose_name='user permissions')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(blank=True, max_length=50, null=True, verbose_name='Ism')),
                ('last_name', models.CharField(blank=True, max_length=50, null=True, verbose_name='Familiya')),
                ('email', models.EmailField(blank=True, max_length=120, null=True, verbose_name='Email')),
                ('created_time', models.DateTimeField(auto_now_add=True, verbose_name="Ro'yxatdan o'tgan vaqti")),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='user', to='account.user')),
            ],
        ),
        migrations.CreateModel(
            name='UploadFile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='upload/')),
            ],
        ),
        migrations.CreateModel(
            name='ProfilePictures',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='account.uploadfile')),
                ('instance', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to='account.profile')),
            ],
        ),
        migrations.CreateModel(
            name='Cofirmation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=6)),
                ('created_time', models.DateTimeField(auto_now_add=True, verbose_name="Qo'shilgan vaqti")),
                ('expiration_time', models.DateTimeField(editable=None, verbose_name='Muddati')),
                ('is_confirmed', models.BooleanField(default=False, verbose_name='Tasdiqlangan')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='verify_codes', to='account.user')),
            ],
        ),
        migrations.CreateModel(
            name='Address',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=100, null=True, verbose_name='Manzil sarlavhasi')),
                ('province', models.CharField(max_length=50, verbose_name='Viloyat')),
                ('district', models.CharField(max_length=50, verbose_name='Tuman / Shahar')),
                ('street', models.CharField(max_length=150, verbose_name="Ko'cha nomi va uy raqami")),
                ('zip_code', models.IntegerField(verbose_name='Pochta indexi')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='account.profile')),
            ],
        ),
    ]
