# Generated by Django 4.0 on 2023-03-15 11:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='cofirmation',
            name='type',
            field=models.CharField(choices=[('register', 'register'), ('resedn', 'resend'), ('password_reset', 'password_reset'), ('order', 'order')], default='register', max_length=20),
        ),
        migrations.AlterField(
            model_name='uploadfile',
            name='file',
            field=models.FileField(upload_to='static/uploads/'),
        ),
    ]
