# Generated by Django 4.0 on 2023-03-17 10:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0003_rename_user_address_profile_alter_cofirmation_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='address',
            name='country',
            field=models.CharField(default='uzbekistan', max_length=50, verbose_name='Mamlakat'),
            preserve_default=False,
        ),
    ]
