# Generated by Django 4.0 on 2023-03-27 06:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('seller', '0006_alter_seller_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='Attribute',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('value', models.CharField(max_length=50)),
                ('status', models.CharField(choices=[('inactive', 'inactive'), ('active', 'active')], default='active', max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Nomi')),
                ('icon', models.URLField(blank=True, null=True, verbose_name='Icon URL')),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='categ', to='product.category')),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Maxsulot nomi')),
                ('description', models.TextField(blank=True, null=True, verbose_name="Ma'lumot")),
                ('price', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Narxi')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('discount', models.PositiveIntegerField(blank=True, null=True, verbose_name='Chagirma (foizda)')),
                ('status', models.CharField(choices=[('inactive', 'inactive'), ('active', 'active')], default='active', max_length=30)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='product_category', to='product.category')),
                ('seller', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='seller.seller')),
            ],
        ),
        migrations.CreateModel(
            name='ProductImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.FileField(upload_to='product_images/')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='product.product')),
            ],
        ),
        migrations.CreateModel(
            name='ProductAttribute',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField(verbose_name='Miqdori')),
                ('status', models.CharField(choices=[('inactive', 'inactive'), ('active', 'active')], default='active', max_length=30)),
                ('attribute', models.ManyToManyField(to='product.Attribute')),
                ('product', models.ManyToManyField(related_name='product_attributes', to='product.Product')),
            ],
        ),
    ]
