# Generated by Django 4.0 on 2023-03-27 12:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0002_uploadimageproduct_remove_productimage_image_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='productimage',
            old_name='product',
            new_name='inctance',
        ),
        migrations.AlterField(
            model_name='attribute',
            name='status',
            field=models.CharField(choices=[('inactive', 'inactive'), ('active', 'active')], default='active', max_length=30),
        ),
        migrations.AlterField(
            model_name='product',
            name='status',
            field=models.CharField(choices=[('inactive', 'inactive'), ('active', 'active')], default='active', max_length=30),
        ),
        migrations.AlterField(
            model_name='productattribute',
            name='status',
            field=models.CharField(choices=[('inactive', 'inactive'), ('active', 'active')], default='active', max_length=30),
        ),
    ]
