# Generated by Django 4.0 on 2023-03-28 11:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0004_rename_images_productimage_image_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attribute',
            name='status',
            field=models.CharField(choices=[('inactive', 'inactive'), ('active', 'active')], default='active', max_length=30),
        ),
        migrations.AlterField(
            model_name='product',
            name='status',
            field=models.CharField(choices=[('inactive', 'inactive'), ('active', 'active')], default='active', max_length=30),
        ),
        migrations.AlterField(
            model_name='productattribute',
            name='attribute',
            field=models.ManyToManyField(blank=True, null=True, to='product.Attribute'),
        ),
        migrations.AlterField(
            model_name='productattribute',
            name='status',
            field=models.CharField(choices=[('inactive', 'inactive'), ('active', 'active')], default='active', max_length=30),
        ),
    ]
