# Generated by Django 4.0 on 2023-03-29 08:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0005_alter_attribute_status_alter_product_status_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attribute',
            name='status',
            field=models.CharField(choices=[('active', 'active'), ('inactive', 'inactive')], default='active', max_length=30),
        ),
        migrations.AlterField(
            model_name='product',
            name='status',
            field=models.CharField(choices=[('active', 'active'), ('inactive', 'inactive')], default='active', max_length=30),
        ),
        migrations.AlterField(
            model_name='productattribute',
            name='quantity',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='Miqdori'),
        ),
        migrations.AlterField(
            model_name='productattribute',
            name='status',
            field=models.CharField(choices=[('active', 'active'), ('inactive', 'inactive')], default='active', max_length=30),
        ),
    ]
