# Generated by Django 4.0 on 2023-03-20 07:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('account', '0004_address_country'),
    ]

    operations = [
        migrations.CreateModel(
            name='Seller',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=60, verbose_name='Egasi ismi')),
                ('last_name', models.CharField(max_length=60, verbose_name='Egasi familiyasi')),
                ('sur_name', models.CharField(max_length=60, verbose_name='Otasining ismi')),
                ('inn', models.CharField(max_length=15, verbose_name='INN raqami')),
                ('shop_name', models.CharField(max_length=200, verbose_name="Do'kon nomi")),
                ('bank_mfo', models.CharField(max_length=8, verbose_name='Bank MFO raqami')),
                ('bank_account', models.CharField(max_length=25, verbose_name='Bank hisob raqami')),
                ('bio', models.TextField(blank=True, null=True, verbose_name='Bio')),
                ('email', models.EmailField(max_length=254, unique=True, verbose_name='Email pochtasi')),
                ('address', models.CharField(blank=True, max_length=250, null=True, verbose_name='Manzil')),
                ('date_joined', models.DateTimeField(auto_now_add=True, verbose_name="Qo'shilgan vaqti")),
                ('shop_picture', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='account.uploadfile')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='account.user')),
            ],
        ),
    ]
