# Generated by Django 4.0 on 2023-03-20 10:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('seller', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='seller',
            old_name='sur_name',
            new_name='surname',
        ),
    ]
