# Generated by Django 4.0 on 2023-03-21 06:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0004_address_country'),
        ('seller', '0002_rename_sur_name_seller_surname'),
    ]

    operations = [
        migrations.CreateModel(
            name='ShopPictures',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='account.uploadfile')),
                ('instance', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='shop', to='seller.seller')),
            ],
        ),
    ]
