# Generated by Django 4.0 on 2023-03-21 08:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('seller', '0003_shoppictures'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='seller',
            name='shop_picture',
        ),
        migrations.AlterField(
            model_name='seller',
            name='bank_account',
            field=models.CharField(max_length=30, verbose_name='Bank hisob raqami'),
        ),
    ]
